# Generated by Django 2.0.7 on 2018-08-18 08:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Qeyd edilmə tarixi')),
                ('article_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Məqaləyə şəkil əlavə edin')),
                ('author', models.ForeignKey(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='Yazıçı')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
